sudo: required
notifications:
  email: false
language: node_js
node_js:
  - '12'
  - '10'
  - '8'
cache: yarn
env:
  global:
    - CXX=g++-4.8
    - NODE_OPTIONS="--max_old_space_size=4096"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.10.1
  - export PATH=$HOME/.yarn/bin:$PATH;
  - rm .yarnrc # this file breaks the build on travis
install: yarn
script:
  - yarn lint
  - yarn test:ci
